### ISSUE TITLE
Doesn't work on node 0.11

### ISSUE THREAD

**Issue by rlidwka** [baudehlo/node-fs-ext#33]
I don't know what they changed, but it doesn't compile anymore:

``` sh
$ ~/node-crypt3/node-v0.11.13-linux-x64/bin/node `which npm` install fs-ext 
npm http GET https://registry.npmjs.org/fs-ext
npm http 200 https://registry.npmjs.org/fs-ext

> fs-ext@0.3.2 install /tmp/node_modules/fs-ext
> node-gyp configure build

make: Entering directory `/tmp/node_modules/fs-ext/build'
  CXX(target) Release/obj.target/fs-ext/fs-ext.o
../fs-ext.cc:91:23: error: variable or field ‘EIO_After’ declared void
 static void EIO_After(uv_work_t *req) {
                       ^
../fs-ext.cc:91:23: error: ‘uv_work_t’ was not declared in this scope
../fs-ext.cc:91:34: error: ‘req’ was not declared in this scope
 static void EIO_After(uv_work_t *req) {
                                  ^
make: *** [Release/obj.target/fs-ext/fs-ext.o] Error 1
make: Leaving directory `/tmp/node_modules/fs-ext/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
```

Node 0.12 is probably going to be released soon, so it'd be nice to be ready for that.
